server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db2?serverTimezone=GMT&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: zjx123456
  jpa:
    show-sql: true # 控制台打印SQL
    hibernate:
      ddl-auto: update