server:
  port: 9090  # 端口

spring:
  application:
    name: service-provider    # 服务名称
  # 配置 Consul 注册中心
  cloud:
    consul:
      # 注册中心访问地址
      host: localhost
      port: 8500
      # 服务提供者信息
      discovery:
        register: false    # 是否注册自己
        instance-id: ${spring.application.name}-01    # 注册实例 id(必须唯一)
        service-name: ${spring.application.name}      # 服务名称
        port: ${server.port}                          # 服务端口
        prefer-agent-address: true                    # 是否使用 ip 地址注册
        ip-address: ${spring.cloud.client.ip-address} # 服务请求 ip


