server:
  port: 8761 #端口

spring:
  application:
    name: eureka-server    #应用名称(同个集群相同)

# 配置eureka server注册中心 单点
eureka:
  instance:
    hostname: eureka01     # 主机名，不配置的时候根据操作系统主机名获取
    prefer-ip-address: true     # 是否使用ip地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port}   # ip:port
  client:
    service-url:                # 注册中心对外暴露的注册地址
      defaultZone: http://localhost:8762/eureka/      # 指向另一个注册中心