server:
  port: 9090    # 端口
  tomcat:
    max-threads: 10     # 降低最大线程数方便模拟高并发

spring:
  application:
    name: order-service-rest    # 应用名称
  # sentinel配置
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: http://localhost:8080
      datasource:   # 配置数据源，动态规则配置
        ds1:
          file:
            file: classpath:flowRule.json   # 对应文件配置
            data-type: json
            rule-type: flow     # 流量控制

# 配置eureka server注册中心
eureka:
  instance:
    prefer-ip-address: true     # 是否使用ip地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port}   # ip:port
  client:
    service-url:                # 注册中心对外暴露的注册地址，集群环境需要所有都注册
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/