spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db1?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: zjx123456
    driver-class-name: com.mysql.cj.jdbc.Driver
magic-api:
  web: /magic/web
  resource:
    type: database
    tableName: magic_config
    prefix: /api
    readonly: false
  sql-column-case: camel
  page-config:
    size: size
    page: page
    default-page: 1
    default-size: 10
server:
  port: 8080