server:
  port: 9091    # 端口

spring:
  application:
    name: service-consumer    # 应用名称

# 局部配置Ribbon负载均衡策略
# service-provider服务
#不同配置只需要类不同即可
#   轮询策略（默认） RoundRobinRule
#   权重轮询策略  WeightResponseTimeRule
#   随机策略  RandomRule
#   最少并发数策略 BestAvaliableRule
#   重试策略  RetryRule
#   可用性敏感策略  AvailabilityFilteringRule
#   区域敏感策略  ZoneAvoidanceRule
service-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    # Ribbon直连方式，指定具体 provider 的服务列表，多个用逗号隔开
    listOfServers: http://localhost:7070,http://localhost:7071

## 关闭Eureka实现Ribbon点对点直连
ribbon:
  eureka:
    enabled: false
