/*
 * This file is generated by jOOQ.
 */
package com.kenshine.generator;


import com.kenshine.generator.tables.User;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Db1 extends SchemaImpl {

    private static final long serialVersionUID = -452861918;

    /**
     * The reference instance of <code>db1</code>
     */
    public static final Db1 DB1 = new Db1();

    /**
     * The table <code>db1.user</code>.
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private Db1() {
        super("db1", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            User.USER);
    }
}
