/*
 * This file is generated by jOOQ.
 */
package com.kenshine.generator;


import com.kenshine.generator.tables.User;


/**
 * Convenience access to all tables in db1
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>db1.user</code>.
     */
    public static final User USER = User.USER;
}
