spring:
  # 配置数据源
  datasource:
    # 数据源类型，使用druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    # 数据库驱动，这里配置高版本mysql驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mybatis_plus_test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: zjx123456


mybatis-plus:
  # MyBatis Mapper所对应的XML文件位置
  # Maven多模块项目的扫描路径需以classpath*:开头（即加载多个jar包下的XML文件）
  mapper-locations: classpath*:mybatis/mapper/*.xml
  # MyBaits别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: com.kenshine.domain
  # 大都为MyBatis原生支持的配置，可以通过MyBatis XML配置文件的形式进行配置
  configuration:
      # 是否开启自动驼峰命名规则映射，MyBatis-Plus中默认值为true，MyBatis中原默认值为false
      map-underscore-to-camel-case: true
      # 将sql及结果输出到日志 与logging 配置选择一个
      # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 全局逻辑删除的实体字段名
      # 如果设置了全局逻辑删除的实体字段名，在实体类中与逻辑删除字段映射的实例域上可以不用加@TableLogic
      # logic-delete-field: deleted
      # 逻辑已删除值，默认为1
      logic-delete-value: 1
      # 逻辑未删除值，默认为0
      logic-not-delete-value: 0



# 输出sql日志，com.rtxtitanv.mapper为mapper接口所在包路径
logging:
  level:
    com:
      kenshine:
        mapper: debug