coherence:
  logging:
    destination: slf4j
    logger-name: MyCoherence
#  sessions:
#    - name: default
#      config: "coherence-cache-config.xml"
#      priority: 1
#    - name: test
#      config: "test-coherence-config.xml"
#      priority: 2
  properties:
    coherence.log.limit: 400
    coherence.log.level: 1