package com.kenshine.javacup.test01;
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Dec 01 13:10:06 CST 2023
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Symbol {
  /* terminals */
  public static final int MINUS = 5;
  public static final int DIVIDE = 7;
  public static final int UMINUS = 9;
  public static final int NUMBER = 12;
  public static final int MOD = 8;
  public static final int SEMI = 3;
  public static final int ERROR = 2;
  public static final int EOF = 0;
  public static final int PLUS = 4;
  public static final int error = 1;
  public static final int RPAREN = 11;
  public static final int TIMES = 6;
  public static final int LPAREN = 10;
}

