quickperf:
  enabled: true
  exclude-urls: /manage,/actuator
  # 维护数据库连接时调用HTTP
  synchronous-http-call:
    while-db-connection-maintained:
      detected: true
  # jvm信息配置
  jvm:
    # 堆分配
    heap-allocation:
      measured: true
      # 限制
      threshold:
        # 开启检测
        detected: true
        # 检测值
        value-in-bytes: 100 000
spring:
  jmx:
    enabled: true
  # 配置数据源
  datasource:
    # 数据库驱动，这里配置高版本mysql驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springboot05?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456