server:
  port: 8761 #端口

spring:
  application:
    name: eureka-server    #应用名称

# 配置eureka server注册中心 单点
eureka:
  instance:
    hostname: localhost     # 主机名，不配置的时候根据操作系统主机名获取
    prefer-ip-address: true     # 是否使用ip地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port}   # ip:port
  client:
    register-with-eureka: false   # 是否将自己注册到注册中心，默认为true，集群可以，单节点需要为false
    fetch-registry: true       # 是否从注册中心获取访问注册信息，默认为true
    service-url:                # 注册中心对外暴露的注册地址
      defaultZone: http://${eureka.instance.instance-id}/eureka/