#h2配置
spring:
  jpa:
    show-sql: true #启用SQL语句的日志记录
    hibernate:
      ddl-auto: update #设置ddl模式
  # 内嵌模式配置(通过java代码启动h2)，只能连接一个客户端，连接多个需要改造成服务器模式
#  datasource:
#    url: jdbc:h2:D:/H2/db/db02 #配置h2数据库的连接地址
#    username: root #配置数据库用户名
#    password: 123456 #配置数据库密码
#    driverClassName: org.h2.Driver #配置JDBC Driver
#    schema: classpath:db/schema.sql #进行该配置后，每次启动程序，程序都会运行resources/db/schema.sql文件，对数据库的结构进行操作。
#    data: classpath:db/data.sql  #进行该配置后，每次启动程序，程序都会运行resources/db/data.sql文件，对数据库的数据操作。
#    platform: h2  #表明使用的数据库平台是h2
  h2: #h2 web console设置
    console:
      settings:
        web-allow-others: true #进行该配置后，h2 web consloe就可以在远程访问了。否则只能在本机访问。
      path: /h2 #进行该配置，你就可以通过YOUR_URL/h2访问h2 web consloe。YOUR_URL是你程序的访问URl。
      enabled: true #进行该配置，程序开启时就会启动h2 web consloe。当然这是默认的，如果你不想在启动程序时启动h2 web consloe，那么就设置为false。
  # 配置服务器连接模式
  datasource:
    url: jdbc:h2:tcp://localhost/D:/H2/db/db05;AUTO_SERVER=TRUE #配置h2数据库的连接地址;此为service链接模式，只允许一个链接，如果想多个链接，比如测试代码链接和页面的h2控制台链接，请使用混合模式链接,将 JDBC URL 后加上 AUTO_SERVER=TRUE
    username: root  #配置数据库用户名
    password: 123456  #配置数据库密码
    driverClassName: org.h2.Driver #配置JDBC Driver
    #schema: classpath:db/schema.sql #进行该配置后，每次启动程序，程序都会运行resources/db/schema.sql文件，对数据库的结构进行操作。
    #data: classpath:db/data.sql  #进行该配置后，每次启动程序，程序都会运行resources/db/data.sql文件，对数据库的数据操作。
    platform: h2  #表明使用的数据库平台是h2