server:
  http_listen_port: 3100
schema_config:
  configs:
    - from: 2021-08-01
      store: boltdb
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h
ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s

storage_config:
  boltdb:
    directory: D:/Java/practice/loki/store/index
  filesystem:
    directory: D:/Java/practice/loki/store/chunks

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  # 每个用户每秒的采样率限制
  ingestion_rate_mb: 32
  # 每个用户允许的采样突发大小
  ingestion_burst_size_mb: 64


chunk_store_config:
  # 最大可查询历史日期 28天,这个时间必须是schema_config中的period的倍数，否则报错。
  max_look_back_period: 672h
# 表的保留期28天
table_manager:
  retention_deletes_enabled: true
  retention_period: 672h
