package com.kenshine.jflex.complex;
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Dec 01 14:45:51 CST 2023
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class MySymbol {
  /* terminals */
  public static final int MINUS = 6;
  public static final int IDENT = 11;
  public static final int DIVIDE = 8;
  public static final int LEFT = 2;
  public static final int NUMBER = 10;
  public static final int EOF = 0;
  public static final int PLUS = 5;
  public static final int RIGHT = 3;
  public static final int ASSIGN = 9;
  public static final int error = 1;
  public static final int TIMES = 7;
  public static final int NEWLINE = 4;
}

