server:
  port: 8080
spring:
  application:
    name: springboot-async
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db3?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: zjx123456
