# javamelody数据监控
javamelody:
  # 启用JavaMelody自动配置
  enabled: true
  # 要从监视中排除的数据源名称（可选，以逗号分隔）
  excluded-datasources: secretSource,topSecretSource
  # 启用对Spring服务和控制器的监视
  spring-monitoring-enabled: true
  # 为JavaMelody（可选）初始化参数
  # 参照地址: https://github.com/javamelody/javamelody/wiki/UserGuide#6-optional-parameters
  init-parameters:
    # 日志http请求
    log: true
    # 从监控中排除图像，css，字体和js网址：
    #url-exclude-pattern: (/webjars/.*|/css/.*|/images/.*|/fonts/.*|/js/.*)
    # 以总位数的http请求：
    #http-transform-pattern: \d+
    # 补充基本身份验证：
    authorized-users: admin:zjx123456
    # 更改默认存储目录：
    #storage-directory: /tmp/javamelody
    # 更改默认的监控路径：
    # monitoring-path: /admin/performance
