server:
  port: 8080

dbBaseDir: F:\derby\db-derby-10.14.2.0-bin  #数据库的根路径

mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.kenshine.derby.domain
  configLocation: classpath:/mybatis-config.xml

spring:
  datasource:
    name: fabric
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:derby:${dbBaseDir}/fabric;create=true
    username: root
    password: root
    driver-class-name: org.apache.derby.jdbc.EmbeddedDriver
    minIdle: 5
    maxActive: 100
    initialSize: 10
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from sysibm.sysdummy1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 50
    removeAbandoned: true
    filters: stat # ,wall,log4j # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    connectionProperties: druid.stat.slowSqlMillis=5000 # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    useGlobalDataSourceStat: true # 合并多个DruidDataSource的监控数据
    druidLoginName: kenshine # 登录druid的账号
    druidPassword: kenshine # 登录druid的密码